language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update "php-coveralls/php-coveralls:^1 | ^2"
  - travis_retry composer install --no-interaction --prefer-dist --no-progress --no-suggest
  - if [ -f vendor/bin/coveralls ]; then ln -s coveralls vendor/bin/php-coveralls; fi

before_script:
  - mkdir -p build/logs

script:
  - composer lint
  - composer phpcs -- --warning-severity=0
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
